### ISSUE TITLE
Investigate using the pre-built binaries

### ISSUE THREAD

**Issue by petemounce** [improbable-eng/perforce-buildkite-plugin#170]
p4python offers pre-built binaries for different platforms (https://www.perforce.com/downloads/helix-core-api-python) which would allow the pip-install step to be skipped and instead rely on binaries found on the host.

We bake our dependencies into our hosts, so this would be a small optimisation for runtime in terms of speed (~10s on first-install).

I'm mostly interested in it as a way to reduce the run-time dependencies (since pip may try to compile dependencies that are not found, at which point that toolchain must be present for that to succeed). I appreciate that on CI machines, that toolchain is likely to be present regardless, but perhaps not at a workable version or setup.

(I'm not expecting this to necessarily be something we do, but thought I'd write it up in case)

**Comment by ca-johnson** [comment]
Hey

Since this is a small optimisation as you noted (10s on first run, 0s thereafter) I would be inclined to keep using the pip packages since:

* pip is the recommended way to install p4python, the packages require more complexity to install and is not simple cross-platform - the responsibility for this is pushed onto the user
* for most versions of python, there are pre-built binaries which are fetched during pip install. you only need the toolchain present to compile p4api when this isn't the case, which can be easily solved by using a version of python which does have these binaries (i.e in practice, this has not caused a real issue)
* it adds an external dependency into the plugin and removes our ability to control which version of p4python is used. currently our only real dependency is that python is on the PATH and `pip` works as expected.
* if we wanted to add another line to requirements.txt, the pip install would be required anyway
* adding this as an option would complicate the code in `hooks/checkout` and potentially add a new configuration option which is something I am keen to avoid to keep things as simple as possible

**Comment by ca-johnson** [comment]
Closing for reasons explained above
